### ISSUE TITLE
How to change path of template?

### ISSUE THREAD

**Issue by ginolon** [karnov/htmltoword#11]
I have to use this code in **application.rb**:

```ruby
Htmltoword.configure do |config|
  config.custom_templates_path = 'C:\web\Rails\project\app\views\documents'
end
```

with this code in the **controller.rb**:

```ruby
format.docx do
        render docx: 'show', word_template: 'mytemplate.docx'
      end
```

Or I can do it better?

Because in the "config.custom_templates_path" **I don't want the absolute path!**

**Comment by anitsirc** [comment]
Have you tried using a relative path? That should work as well

**Comment by ginolon** [comment]
How to do?

**Comment by anitsirc** [comment]
Just like any other relative path, assuming the folder project is the root folder of your project it should look something like 

```
Htmltoword.configure do |config|
  config.custom_templates_path = 'app\views\documents'
end
```

**Comment by ginolon** [comment]
Great! It works! Thanks!
