### ISSUE TITLE
Is it possible to hide the table borders?

### ISSUE THREAD

**Issue by ginolon** [karnov/htmltoword#14]
Is it possible to hide the table borders?

Is it possible to change the color to white or transparent?

**Comment by anitsirc** [comment]
Hi again, 

By default tables have no borders. A table like the following won't show any borders
```
<table>
  <tr>
    <td>Cell 1</td>
    <td>Cell 2</td>
  </tr>
</table>
```

If you use the table-bordered class or have defined the border attribute greater than 0, then it will show the borders, just as the html
