### ISSUE TITLE
Releases on rubygems and update readme.

### ISSUE THREAD

**Issue by ceritium** [karnov/htmltoword#18]
The readme talk about the method `create_and_save` but the latest rubygem version does not includes this.

**Comment by anitsirc** [comment]
Yes, my bad. I forgot to bump the rubygems version. I need to make a few more fixes and then I'll bump it again. 

You can always point to master in your Gemfile if you want to make sure you have the latest version

**Comment by francois2metz** [comment]
Can be closed.
