### ISSUE TITLE
ALL CAPS?

### ISSUE THREAD

**Issue by duffyjp** [karnov/htmltoword#19]
I'm getting started with your gem and ran into some issues.  The main thing is the template.  It looks like most of the default header tags are ALL CAPS.  I tried using my own template file, but it is silently ignored.

If a word_template: "foo.docx" is not found, I think you should throw an exception to help users find their problem.  I'm not sure from the README where my template is supposed to be.  I'd like it in the view right next to the docx.erb file.  Even if I specify an absolute path it's ignored.

```ruby
  def show
    respond_to do |format|
      format.html
      format.docx do
        render docx: 'show', filename: "#{@person.last_name.downcase}_cv_#{Date.today}", word_template: "show_template.docx"
      end
    end
  end
```

**Comment by anitsirc** [comment]
Hi, 

The default template is set to have headers in Caps. 

You can customize your own default template that fits your needs and then specify where your custom templates will be. It could be in an initializer (e.g. config/initializers/htmltoword.rb) or somewhere else before you make the calls to generate the document. 

You should write something like 
```
Htmltoword.configure do |config|
  config.custom_templates_path = 'path_to_your_templates'
  # Some other configuration... 
end
```
or 
```
Htmltoword.config.custom_templates_path = 'path_to_your_templates'
```
