### ISSUE TITLE
create_and_save creates corrupted docx files on win32 platforms

### ISSUE THREAD

**Issue by rafez** [karnov/htmltoword#22]
Using latest version available on git (0.4.4), and create a simple ruby program.

`require 'htmltoword'`
`file = Htmltoword::Document.create_and_save( "<html><head><title>Simple title</title></head><body>Hello docx</body></html>", "out-001.docx" )`

Running this on Mac OS-X works, fine and generates a docx file that can be opened. However generating and opening the same file on Win32 (Windows XP) results in a corrupted file.

Ruby version = 2.0.0p195 (but could be tested on more recent rubies)

**Comment by rafez** [comment]
Have managed to develop a bug fix for this. Issue lies in 
`lib\htmltoword\document.rb` line 14
replace 
```ruby
         File.open(file_path, "w") do |out|
```
with
```ruby
        File.open(file_path, "wb") do |out| 
`
To ensure that files are written back in binary.
I'll try and issue a git pull request for this change,

**Comment by anitsirc** [comment]
Great!

**Comment by rafez** [comment]
Code merged into master. Closing issue.

**Comment by rafez** [comment]
In the Rubygem v0.4.4 - this bug has regressed back to the broken version, without the 
```ruby
File.open(file_path, "wb") do |out| 
```
It appears the document.rb in the gem is not the same as that on github, even if you point your Gemfile to github as in
```
gem 'htmltoword', :git => "https://github.com/karnov/htmltoword.git"
```

**Comment by anitsirc** [comment]
I just downloaded and unpacked the gem straight from rubygems, the ```create_and_save``` method does open the file with the ```wb``` options, maybe it's something else? I don't use windows, so it's a bit hard to debug :confused:

**Comment by rafez** [comment]
I did the same as you, and yes, the extracted gem has the ```wb``` is correctly there. Did a bundle clean -force and reinstalled all gems from scratch, all seems to be ok now. Very odd. Closing call for the moment, unless I can repeat.
