### ISSUE TITLE
create_and_save not found

### ISSUE THREAD

**Issue by samstickland** [karnov/htmltoword#29]
In 0.4.2 I don't have the create_and_save method

2.2.1 :009 > Htmltoword::Document.methods.select { |m| m=~ /create/ }
 => [:create, :create_with_content] 

Do I need to track master? The document implies this is available in 0.4+

**Comment by fran-worley** [comment]
As per #18 it looks like the version on RubyGems is not up to date so you will need to track master for this.

**Comment by anitsirc** [comment]
Hey! latest version 0.4.4 does have it included :blush:
