### ISSUE TITLE
Default template contains misleading metadata

### ISSUE THREAD

**Issue by benbalter** [karnov/htmltoword#3]
The default template contains some misleading metadata:

![screen shot 2015-05-28 at 1 24 14 pm](https://cloud.githubusercontent.com/assets/282759/7866346/e066776e-053c-11e5-806f-481a00d3328d.png)

Specifically, the "template", and author, as well as some properties that aren't necessary:

![screen shot 2015-05-28 at 1 25 42 pm](https://cloud.githubusercontent.com/assets/282759/7866396/304d3042-053d-11e5-97cc-50662552b5fc.png)

While it doesn't affect the output, it can be a bit misleading when sending the created document to third-parties.

Glad to submit a pull request, but wanted to check in first before I did, in case it was purposeful.

**Comment by MadsBuus** [comment]
Please do, I don't think any of that metadata is necessary in there (We are not using it).
Probably Cristina just created an 'empty' document.
I can the that the 'tax guide.dotx' comes from the current project we are using it for :)

**Comment by benbalter** [comment]
Done via https://github.com/karnov/htmltoword/issues/5.
