### ISSUE TITLE
Default template is in Danish

### ISSUE THREAD

**Issue by benbalter** [karnov/htmltoword#4]
The default template is set to Danish (which took me a bit to figure out). Is it possible to tell the default template to respect the system default language (rather than hard coding one specific one)?

**Comment by MadsBuus** [comment]
Yes, I guess that is probably a bit 'local' for a default :)
Could you create a more general one?
It is quite easy to replace with your own. Kinda the whole point

**Comment by benbalter** [comment]
> Could you create a more general one?

Glad to. Will wait to see what happens with https://github.com/karnov/htmltoword/pull/5 to avoid a merge conflict. It looks like it's just a matter of removing the `<w:lang>` tags from the style (which would then fall back to the system default).

**Comment by anitsirc** [comment]
Hi @benbalter, in https://github.com/karnov/htmltoword/pull/6 I'm changing again the default template since the one you provided it's broken. I think I removed all or at least most of the meta data, regarding templates, author, etc. But please do check if it still has some extra things

**Comment by tobiashm** [comment]
@anitsirc Could you also include the exploded version, so it matches / can be recreated?

**Comment by anitsirc** [comment]
@tobiashm Updated again both the docx and the exploded folder https://github.com/karnov/htmltoword/commit/f5f7eff36682449aa8f8f1e78d46114a83e5e28d

The default template was generated with Ben script, and it has no properties regarding author, company, etc. so it should take the system one.
