### ISSUE TITLE
Bug in rails 5

### ISSUE THREAD

**Issue by ariawanzero** [karnov/htmltoword#51]
Hey I'm trying to use this gem with my rails project, i'm already following all your tutor but i when i change template to .docx.erb it not downloaded and in log development it keep showing DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::DOCX` to `Mime[:docx]` when i use format.docx please help

**Comment by francois2metz** [comment]
Fixed by #54.
